### ISSUE TITLE
stuck on "connecting database..."

### ISSUE THREAD

**Issue by mister-monster** [mrusme/superhighway84#66]
So after a long process of attempting to get this software to run, raising my send buffer to 2500000 and dealing with IPFS versions and what not, upon launch of the superhighway84 binary it gets stuck on "connecting database..." I have no idea what to make of this, i was able to sort out all the other issues with my system and IPFS and their dependancy shenanigans but I have no information to work with beyond what the superhighway84 prompt is giving me upon initialization.

Thanks.

**Comment by mister-monster** [comment]
update: upon waiting for a while, like 15 minutes, i get the following error:

```
2023/06/27 18:51:32 unable to open database: unable to fetch database manifest: context deadline exceeded
panic: unable to open database: unable to fetch database manifest: context deadline exceeded

	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1459c07]

goroutine 1 [running]:
github.com/mrusme/superhighway84/database.(*Database).Disconnect(0xc0024621e0)
	/home/runner/work/superhighway84/superhighway84/database/database.go:221 +0x27
panic({0x15d46a0, 0xc009710cc0})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x207
log.Panicln({0xc001645f48?, 0xc00355a540?, 0xc0000c70e0?})
	/opt/hostedtoolcache/go/1.18.9/x64/src/log/log.go:399 +0x65
main.main()
	/home/runner/work/superhighway84/superhighway84/superhighway84.go:125 +0x8dd
```

**Comment by m00E10** [comment]
same issue here

**Comment by mrusme** [comment]
I have just restarted the VPS that runs a permanent-online instance of SH84, which should help with connecting. Also, have you tried [this](https://github.com/mrusme/superhighway84#connectivity)? In any way, please try again now and report of connection was successfully established or you're still unable to connect.

**Comment by goodspeed34** [comment]
also here, already have auto relay enabled. It's running on a tilde server. So if you want to investigate this issue on this machine, I can make an account.

```
goodspeed@tilde:~$ superhighway84 
2023/07/03 17:28:18 loading configuration ...
2023/07/03 17:28:18 initializing logger ...
2023/07/03 17:28:18 initializing cache ...
2023/07/03 17:28:18 initializing TUI and loading database, please wait ...
2023/07/03 17:28:19 initializing database ...
2023/07/03 17:28:20 connecting database ...
2023/07/03 17:38:20 unable to open database: unable to fetch database manifest: context deadline exceeded
panic: unable to open database: unable to fetch database manifest: context deadline exceeded

        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1459c07]

goroutine 1 [running]:
github.com/mrusme/superhighway84/database.(*Database).Disconnect(0xc001f761e0)
        /home/runner/work/superhighway84/superhighway84/database/database.go:221 +0x27
panic({0x15d46a0, 0xc003f07b80})
        /opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x207
log.Panicln({0xc0008e7f48?, 0xc0034e9a40?, 0xc000095860?})
        /opt/hostedtoolcache/go/1.18.9/x64/src/log/log.go:399 +0x65
main.main()
        /home/runner/work/superhighway84/superhighway84/superhighway84.go:125 +0x8dd
```

**Comment by mrusme** [comment]
@goodspeed34 which version of SH84 are you running?

**Comment by goodspeed34** [comment]
I'm using the lastest release. https://github.com/mrusme/superhighway84/releases/tag/v0.2.4

**Comment by mrusme** [comment]
The instance that I've been running on a VPS has been shut off a while ago and I didn't turn it back on due to the lack of interest from people to run this project and contribute to the network. Hence I would assume that the reason you're unable to connect is because there simply are no peers available right now.

Of course Superhighway84 should launch nevertheless, unfortunately it seems like OrbitDB/IPFS **requires** at least some peer to be available for the very first sync. I could invest some time to build in a workaround that would make the TUI launch and simply be empty for the time being, it would however not change the fact that the network of peers is currently defacto not available and hence nobody will be able to sync the official database.

Having that said, everyone is free to set up their own database/network and host their own peers.

**Comment by krionical** [comment]
Is this still the case in 2025? I always thought this was a neat project and it'd be a shame to see it do nothing.
